package io.github.yasmramos.warmup.processor;

import io.github.yasmramos.warmup.annotations.Inject;
import io.github.yasmramos.warmup.annotations.Lazy;
import org.objectweb.asm.*;

import javax.lang.model.element.*;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates bytecode for CompiledFactory implementations using ASM at compile-time.
 * 
 * This class produces the same factory structure as AsmJITCompiler.generateFactoryBytecode,
 * but works with TypeElement/TypeMirror instead of Class<?> since at compile-time the
 * user classes are not yet compiled and no Class objects are available.
 * 
 * Generated factory structure:
 * - Fields: dep0, dep1, ... for wired dependencies (type Object)
 * - Constructor: default empty constructor
 * - wire(Object[]): stores dependencies in fields
 * - get(): creates bean instance using wired dependencies (no Object[] allocation)
 * - create(Object...): fallback method for backward compatibility
 * - getBeanType(): returns the bean Class
 * - getDependencyCount(): returns total dependency count
 */
public class FactoryBytecodeGenerator {

    private final MessagerAdapter messager;
    private final Elements elements;

    public FactoryBytecodeGenerator(MessagerAdapter messager, Elements elements) {
        this.messager = messager;
        this.elements = elements;
    }

    public FactoryBytecodeGenerator(MessagerAdapter messager) {
        this.messager = messager;
        this.elements = null;
    }

    /**
     * Generates bytecode for a class-level bean factory.
     * 
     * @param beanClass the TypeElement of the bean class
     * @param scope the scope of the bean (SINGLETON, PROTOTYPE, etc.)
     * @param explicitName the explicit bean name if provided
     * @param constructor the injectable constructor (may be null for no-arg)
     * @param injectFields list of fields annotated with @Inject
     * @param injectMethods list of methods annotated with @Inject (for setter injection)
     * @return the generated bytecode
     */
    public byte[] generateFactoryForClassBytecode(
            TypeElement beanClass,
            String scope,
            String explicitName,
            ExecutableElement constructor,
            List<VariableElement> injectFields,
            List<ExecutableElement> injectMethods) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

        String packageName = getPackageName(beanClass);
        String className = beanClass.getSimpleName().toString();
        String binaryName = getBinaryName(beanClass);
        String factoryClassName;
        
        // For nested classes, use the binary name (with $) to create a unique factory name
        if (beanClass.getNestingKind().isNested()) {
            // For nested classes, create factory name from binary name
            String binaryNameForFactory = binaryName.replace('.', '/');
            factoryClassName = binaryNameForFactory + "$$WarmupFactory";
        } else {
            factoryClassName = packageName.isEmpty() ? className + "$$WarmupFactory" : packageName.replace('.', '/') + "/" + className + "$$WarmupFactory";
        }
        
        String beanInternalName = binaryName.replace('.', '/');
        String interfaceName = "io/github/yasmramos/warmup/core/jit/CompiledFactory";

        // Class signature: CompiledFactory<BeanType>
        String signature = "L" + interfaceName + "<L" + beanInternalName + ";>;";

        // Class declaration: public final class Bean$$WarmupFactory implements CompiledFactory<BeanType>
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL, factoryClassName, null,
                "java/lang/Object", new String[]{interfaceName});

        // Collect all dependencies: constructor params + @Inject fields + @Inject method params
        List<? extends VariableElement> constructorParams = constructor != null ? constructor.getParameters() : new ArrayList<>();
        
        // Separate lazy and non-lazy field injections
        List<VariableElement> nonLazyFields = new ArrayList<>();
        List<VariableElement> lazyFields = new ArrayList<>();
        for (VariableElement field : injectFields) {
            if (field.getAnnotation(Lazy.class) != null) {
                lazyFields.add(field);
            } else {
                nonLazyFields.add(field);
            }
        }
        
        // Separate lazy and non-lazy method injections
        List<ExecutableElement> nonLazyMethods = new ArrayList<>();
        List<ExecutableElement> lazyMethods = new ArrayList<>();
        for (ExecutableElement method : injectMethods) {
            if (method.getAnnotation(Lazy.class) != null) {
                lazyMethods.add(method);
            } else {
                nonLazyMethods.add(method);
            }
        }
        
        // Count total method parameters for dependency counting (all deps, including lazy)
        int nonLazyMethodParamCount = 0;
        for (ExecutableElement method : nonLazyMethods) {
            nonLazyMethodParamCount += method.getParameters().size();
        }
        int lazyMethodParamCount = 0;
        for (ExecutableElement method : lazyMethods) {
            lazyMethodParamCount += method.getParameters().size();
        }
        
        int totalDeps = constructorParams.size() + nonLazyFields.size() + nonLazyMethodParamCount + lazyFields.size() + lazyMethodParamCount;
        int nonLazyDeps = constructorParams.size() + nonLazyFields.size() + nonLazyMethodParamCount;
        int lazyDeps = lazyFields.size() + lazyMethodParamCount;

        // Declare fields for wired dependencies (dep0, dep1, ...)
        for (int i = 0; i < totalDeps; i++) {
            cw.visitField(Opcodes.ACC_PRIVATE, "dep" + i, "Ljava/lang/Object;", null, null);
        }

        // Default constructor
        MethodVisitor ctor = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitInsn(Opcodes.RETURN);
        ctor.visitMaxs(1, 1);
        ctor.visitEnd();

        // wire method: public void wire(CompiledFactory<?>[] dependencyFactories)
        if (totalDeps > 0) {
            MethodVisitor wv = cw.visitMethod(Opcodes.ACC_PUBLIC, "wire",
                    "([Lio/github/yasmramos/warmup/core/jit/CompiledFactory;)V",
                    null, null);
            wv.visitCode();

            // For each dependency: this.dep[i] = dependencyFactories[i]
            for (int i = 0; i < totalDeps; i++) {
                // Load 'this'
                wv.visitVarInsn(Opcodes.ALOAD, 0);
                // Load dependencyFactories array
                wv.visitVarInsn(Opcodes.ALOAD, 1);
                // Push index
                wv.visitLdcInsn(i);
                // Load element: dependencyFactories[i]
                wv.visitInsn(Opcodes.AALOAD);
                // Store in field: this.dep{i}
                wv.visitFieldInsn(Opcodes.PUTFIELD, factoryClassName, "dep" + i, "Ljava/lang/Object;");
            }

            wv.visitInsn(Opcodes.RETURN);
            wv.visitMaxs(3, 2);
            wv.visitEnd();
        }

        // get method: public Object get()
        MethodVisitor gv = cw.visitMethod(Opcodes.ACC_PUBLIC, "get",
                "()Ljava/lang/Object;",
                "()T" + ";" + beanInternalName + ";", null);
        gv.visitCode();

        // Create new instance of bean
        gv.visitTypeInsn(Opcodes.NEW, beanInternalName);
        gv.visitInsn(Opcodes.DUP);

        // Push constructor arguments from wired fields
        for (int i = 0; i < constructorParams.size(); i++) {
            // Load 'this'
            gv.visitVarInsn(Opcodes.ALOAD, 0);
            // Get field: this.dep{i}
            gv.visitFieldInsn(Opcodes.GETFIELD, factoryClassName, "dep" + i, "Ljava/lang/Object;");
            // Cast to CompiledFactory
            gv.visitTypeInsn(Opcodes.CHECKCAST, "io/github/yasmramos/warmup/core/jit/CompiledFactory");
            // Invoke get() to resolve the instance
            gv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "io/github/yasmramos/warmup/core/jit/CompiledFactory", "get", "()Ljava/lang/Object;", true);
            // Cast to dependency type (unboxes primitive parameters)
            emitCastToDeclaredType(gv, constructorParams.get(i).asType());
        }

        // Build constructor descriptor
        StringBuilder ctorDescBuilder = new StringBuilder("(");
        for (VariableElement param : constructorParams) {
            ctorDescBuilder.append(getDescriptor(param.asType()));
        }
        ctorDescBuilder.append(")V");
        String constructorDescriptor = ctorDescBuilder.toString();

        // Invoke constructor
        gv.visitMethodInsn(Opcodes.INVOKESPECIAL, beanInternalName, "<init>", constructorDescriptor, false);

        // Inject @Inject fields from non-lazy wired dependencies only
        int currentFieldIndex = constructorParams.size();
        for (int i = 0; i < nonLazyFields.size(); i++) {
            VariableElement field = nonLazyFields.get(i);
            String fieldName = field.getSimpleName().toString();
            int fieldIndex = currentFieldIndex + i;

            // Load instance (already on stack after constructor call)
            gv.visitInsn(Opcodes.DUP);
            // Load 'this' (the factory)
            gv.visitVarInsn(Opcodes.ALOAD, 0);
            // Get field: this.dep{fieldIndex}
            gv.visitFieldInsn(Opcodes.GETFIELD, factoryClassName, "dep" + fieldIndex, "Ljava/lang/Object;");
            // Cast to CompiledFactory
            gv.visitTypeInsn(Opcodes.CHECKCAST, "io/github/yasmramos/warmup/core/jit/CompiledFactory");
            // Invoke get() to resolve the instance
            gv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "io/github/yasmramos/warmup/core/jit/CompiledFactory", "get", "()Ljava/lang/Object;", true);
            // Cast to field type (unboxes primitive fields)
            TypeMirror fieldType = field.asType();
            emitCastToDeclaredType(gv, fieldType);
            // Put field: instance.fieldName = value
            String fieldDescriptor = getDescriptor(fieldType);
            gv.visitFieldInsn(Opcodes.PUTFIELD, beanInternalName, fieldName, fieldDescriptor);
        }

        // Invoke @Inject methods (non-lazy only) after field injection
        int methodParamStartIndex = constructorParams.size() + nonLazyFields.size();
        for (ExecutableElement method : nonLazyMethods) {
            String methodName = method.getSimpleName().toString();
            List<? extends VariableElement> methodParams = method.getParameters();
            
            // Build method descriptor
            StringBuilder methodDescBuilder = new StringBuilder("(");
            for (VariableElement param : methodParams) {
                methodDescBuilder.append(getDescriptor(param.asType()));
            }
            methodDescBuilder.append(")V");
            String methodDescriptor = methodDescBuilder.toString();
            
            // Load instance (already on stack)
            gv.visitInsn(Opcodes.DUP);
            
            // Push method arguments from wired deps
            int currentParamIndex = methodParamStartIndex;
            for (VariableElement param : methodParams) {
                // Load 'this' (the factory)
                gv.visitVarInsn(Opcodes.ALOAD, 0);
                // Get field: this.dep{currentParamIndex}
                gv.visitFieldInsn(Opcodes.GETFIELD, factoryClassName, "dep" + currentParamIndex, "Ljava/lang/Object;");
                // Cast to CompiledFactory
                gv.visitTypeInsn(Opcodes.CHECKCAST, "io/github/yasmramos/warmup/core/jit/CompiledFactory");
                // Invoke get() to resolve the instance
                gv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "io/github/yasmramos/warmup/core/jit/CompiledFactory", "get", "()Ljava/lang/Object;", true);
                // Cast to parameter type (unboxes primitive parameters)
                emitCastToDeclaredType(gv, param.asType());
                currentParamIndex++;
            }
            
            // Invoke the inject method
            gv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, beanInternalName, methodName, methodDescriptor, false);
            
            // Update start index for next method
            methodParamStartIndex += methodParams.size();
        }

        // Return the created instance
        gv.visitInsn(Opcodes.ARETURN);
        gv.visitMaxs(2 + constructorParams.size(), 1);
        gv.visitEnd();

        // create method: public Object create(Object... dependencies)
        MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "create",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                null, null);
        mv.visitCode();

        // Create new instance of bean
        mv.visitTypeInsn(Opcodes.NEW, beanInternalName);
        mv.visitInsn(Opcodes.DUP);

        // Push constructor arguments from dependencies array
        for (int i = 0; i < constructorParams.size(); i++) {
            // Load dependencies array
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            // Push index
            mv.visitLdcInsn(i);
            // Load element: dependencies[i]
            mv.visitInsn(Opcodes.AALOAD);
            // Cast to dependency type (unboxes primitive parameters)
            emitCastToDeclaredType(mv, constructorParams.get(i).asType());
        }

        // Invoke constructor
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, beanInternalName, "<init>", constructorDescriptor, false);

        // Inject @Inject fields from dependencies array (after constructor params)
        for (int i = 0; i < injectFields.size(); i++) {
            VariableElement field = injectFields.get(i);
            String fieldName = field.getSimpleName().toString();
            int fieldIndex = constructorParams.size() + i;

            // Load instance (already on stack after constructor call)
            mv.visitInsn(Opcodes.DUP);
            // Load dependencies array
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            // Push index
            mv.visitLdcInsn(fieldIndex);
            // Load element: dependencies[fieldIndex]
            mv.visitInsn(Opcodes.AALOAD);
            // Cast to field type (unboxes primitive fields)
            TypeMirror fieldType = field.asType();
            emitCastToDeclaredType(mv, fieldType);
            // Put field: instance.fieldName = value
            String fieldDescriptor = getDescriptor(fieldType);
            mv.visitFieldInsn(Opcodes.PUTFIELD, beanInternalName, fieldName, fieldDescriptor);
        }

        // Invoke @Inject methods after field injection (create method path)
        int createMethodParamStartIndex = constructorParams.size() + injectFields.size();
        for (ExecutableElement method : injectMethods) {
            String methodName = method.getSimpleName().toString();
            List<? extends VariableElement> methodParams = method.getParameters();
            
            // Build method descriptor
            StringBuilder methodDescBuilder = new StringBuilder("(");
            for (VariableElement param : methodParams) {
                methodDescBuilder.append(getDescriptor(param.asType()));
            }
            methodDescBuilder.append(")V");
            String methodDescriptor = methodDescBuilder.toString();
            
            // Load instance (already on stack)
            mv.visitInsn(Opcodes.DUP);
            
            // Push method arguments from dependencies array
            int currentParamIndex = createMethodParamStartIndex;
            for (VariableElement param : methodParams) {
                // Load dependencies array
                mv.visitVarInsn(Opcodes.ALOAD, 1);
                // Push index
                mv.visitLdcInsn(currentParamIndex);
                // Load element: dependencies[currentParamIndex]
                mv.visitInsn(Opcodes.AALOAD);
                // Cast to parameter type (unboxes primitive parameters)
                emitCastToDeclaredType(mv, param.asType());
                currentParamIndex++;
            }
            
            // Invoke the inject method
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, beanInternalName, methodName, methodDescriptor, false);
            
            // Update start index for next method
            createMethodParamStartIndex += methodParams.size();
        }

        // Return the created instance
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(2 + constructorParams.size(), 2);
        mv.visitEnd();

        // injectDeferred method: public void injectDeferred(Object instance, Object... deferredDependencies)
        // Only generate this method if there are lazy dependencies
        if (lazyDeps > 0) {
            MethodVisitor idv = cw.visitMethod(Opcodes.ACC_PUBLIC, "injectDeferred",
                    "(Ljava/lang/Object;[Ljava/lang/Object;)V",
                    null, null);
            idv.visitCode();
            
            // Cast instance to bean type
            idv.visitVarInsn(Opcodes.ALOAD, 1);
            idv.visitTypeInsn(Opcodes.CHECKCAST, beanInternalName);
            
            // Inject lazy fields from deferred dependencies array
            int lazyFieldIndex = 0;
            for (int i = 0; i < lazyFields.size(); i++) {
                VariableElement field = lazyFields.get(i);
                String fieldName = field.getSimpleName().toString();
                
                // Load instance (already on stack after cast)
                idv.visitInsn(Opcodes.DUP);
                // Load deferredDependencies array
                idv.visitVarInsn(Opcodes.ALOAD, 2);
                // Push index
                idv.visitLdcInsn(lazyFieldIndex);
                // Load element: deferredDependencies[lazyFieldIndex]
                idv.visitInsn(Opcodes.AALOAD);
                // Cast to field type (unboxes primitive fields)
                TypeMirror fieldType = field.asType();
                emitCastToDeclaredType(idv, fieldType);
                // Put field: instance.fieldName = value
                String fieldDescriptor = getDescriptor(fieldType);
                idv.visitFieldInsn(Opcodes.PUTFIELD, beanInternalName, fieldName, fieldDescriptor);
                
                lazyFieldIndex++;
            }
            
            // Invoke lazy @Inject methods after field injection
            int lazyMethodParamStartIndex = lazyFields.size();
            for (ExecutableElement method : lazyMethods) {
                String methodName = method.getSimpleName().toString();
                List<? extends VariableElement> methodParams = method.getParameters();
                
                // Build method descriptor
                StringBuilder methodDescBuilder = new StringBuilder("(");
                for (VariableElement param : methodParams) {
                    methodDescBuilder.append(getDescriptor(param.asType()));
                }
                methodDescBuilder.append(")V");
                String methodDescriptor = methodDescBuilder.toString();
                
                // Load instance (already on stack)
                idv.visitInsn(Opcodes.DUP);
                
                // Push method arguments from deferred dependencies array
                int currentParamIndex = lazyMethodParamStartIndex;
                for (VariableElement param : methodParams) {
                    // Load deferredDependencies array
                    idv.visitVarInsn(Opcodes.ALOAD, 2);
                    // Push index
                    idv.visitLdcInsn(currentParamIndex);
                    // Load element: deferredDependencies[currentParamIndex]
                    idv.visitInsn(Opcodes.AALOAD);
                    // Cast to parameter type (unboxes primitive parameters)
                    emitCastToDeclaredType(idv, param.asType());
                    currentParamIndex++;
                }
                
                // Invoke the inject method
                idv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, beanInternalName, methodName, methodDescriptor, false);
                
                // Update start index for next method
                lazyMethodParamStartIndex += methodParams.size();
            }
            
            idv.visitInsn(Opcodes.RETURN);
            idv.visitMaxs(3, 3);
            idv.visitEnd();
        }

        // getBeanType method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getBeanType",
                "()Ljava/lang/Class;",
                "()Ljava/lang/Class<T>;", null);
        mv.visitCode();
        mv.visitLdcInsn(Type.getType("L" + beanInternalName + ";"));
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        // getDependencyCount method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getDependencyCount",
                "()I", null, null);
        mv.visitCode();
        mv.visitLdcInsn(totalDeps);
        mv.visitInsn(Opcodes.IRETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        cw.visitEnd();

        return cw.toByteArray();
    }

    /**
     * Generates bytecode for a @Bean method factory.
     * 
     * @param factoryClass the TypeElement of the @Factory class
     * @param method the @Bean method
     * @param beanAnnotation the @Bean annotation
     * @return the generated bytecode
     */
    public byte[] generateFactoryForMethodBytecode(
            TypeElement factoryClass,
            ExecutableElement method,
            io.github.yasmramos.warmup.annotations.Bean beanAnnotation) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

        String packageName = getPackageName(factoryClass);
        String factoryClassNameStr = factoryClass.getSimpleName().toString();
        String methodName = method.getSimpleName().toString();
        String factoryInternalName = packageName.isEmpty() ? factoryClassNameStr : packageName.replace('.', '/') + "/" + factoryClassNameStr;
        
        TypeMirror returnTypeMirror = method.getReturnType();
        String returnTypeName = returnTypeMirror.toString();
        // A primitive-returning @Bean method is boxed by the generated factory, so the bean type
        // exposed through the generic signature and getBeanType() is the wrapper class
        // (e.g. int -> java.lang.Integer), never the primitive descriptor.
        boolean primitiveReturn = returnTypeMirror.getKind().isPrimitive()
                && returnTypeMirror.getKind() != TypeKind.VOID;
        String returnTypeInternalName = primitiveReturn
                ? boxedInternalName(returnTypeMirror.getKind())
                : getInternalName(returnTypeMirror);
        String returnTypeFqn = getFullyQualifiedTypeName(returnTypeMirror);
        
        String generatedFactoryName = packageName.isEmpty() ? factoryClassNameStr + "$$" + methodName + "$$WarmupFactory" 
                : packageName.replace('.', '/') + "/" + factoryClassNameStr + "$$" + methodName + "$$WarmupFactory";

        String interfaceName = "io/github/yasmramos/warmup/core/jit/CompiledFactory";

        // Class signature
        String signature = "L" + interfaceName + "<L" + returnTypeInternalName + ";>;";

        // Class declaration
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL, generatedFactoryName, null,
                "java/lang/Object", new String[]{interfaceName});

        // Field for caching the factory instance
        cw.visitField(Opcodes.ACC_PRIVATE, "factoryInstance", "L" + factoryInternalName + ";", null, null);

        // Get method parameters
        List<? extends VariableElement> parameters = method.getParameters();

        // Declare fields for dependency factories
        for (int i = 0; i < parameters.size(); i++) {
            cw.visitField(Opcodes.ACC_PRIVATE, "dep" + i, "Ljava/lang/Object;", null, null);
        }

        // Default constructor
        MethodVisitor ctor = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitInsn(Opcodes.RETURN);
        ctor.visitMaxs(1, 1);
        ctor.visitEnd();

        // wire method
        if (!parameters.isEmpty()) {
            MethodVisitor wv = cw.visitMethod(Opcodes.ACC_PUBLIC, "wire",
                    "([Lio/github/yasmramos/warmup/core/jit/CompiledFactory;)V",
                    null, null);
            wv.visitCode();

            for (int i = 0; i < parameters.size(); i++) {
                wv.visitVarInsn(Opcodes.ALOAD, 0);
                wv.visitVarInsn(Opcodes.ALOAD, 1);
                wv.visitLdcInsn(i);
                wv.visitInsn(Opcodes.AALOAD);
                wv.visitFieldInsn(Opcodes.PUTFIELD, generatedFactoryName, "dep" + i, "Ljava/lang/Object;");
            }

            wv.visitInsn(Opcodes.RETURN);
            wv.visitMaxs(3, 2);
            wv.visitEnd();
        }

        // get method
        MethodVisitor gv = cw.visitMethod(Opcodes.ACC_PUBLIC, "get",
                "()Ljava/lang/Object;",
                "()TT;", null);
        gv.visitCode();

        // Check if factoryInstance == null
        gv.visitVarInsn(Opcodes.ALOAD, 0);
        gv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");
        Label nullCheck = new Label();
        gv.visitJumpInsn(Opcodes.IFNONNULL, nullCheck);

        // Create new factory instance
        gv.visitVarInsn(Opcodes.ALOAD, 0);
        gv.visitTypeInsn(Opcodes.NEW, factoryInternalName);
        gv.visitInsn(Opcodes.DUP);
        gv.visitMethodInsn(Opcodes.INVOKESPECIAL, factoryInternalName, "<init>", "()V", false);
        gv.visitFieldInsn(Opcodes.PUTFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        gv.visitLabel(nullCheck);

        // Load factory instance
        gv.visitVarInsn(Opcodes.ALOAD, 0);
        gv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        // Push method arguments from wired deps
        for (int i = 0; i < parameters.size(); i++) {
            gv.visitVarInsn(Opcodes.ALOAD, 0);
            gv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "dep" + i, "Ljava/lang/Object;");
            // Cast to CompiledFactory
            gv.visitTypeInsn(Opcodes.CHECKCAST, "io/github/yasmramos/warmup/core/jit/CompiledFactory");
            // Invoke get() to resolve the instance
            gv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "io/github/yasmramos/warmup/core/jit/CompiledFactory", "get", "()Ljava/lang/Object;", true);
            // Cast to parameter type (unboxes primitive parameters)
            emitCastToDeclaredType(gv, parameters.get(i).asType());
        }

        // Build method descriptor
        StringBuilder methodDescBuilder = new StringBuilder("(");
        for (VariableElement param : parameters) {
            methodDescBuilder.append(getDescriptor(param.asType()));
        }
        methodDescBuilder.append(")").append(getDescriptor(returnTypeMirror));
        String methodDescriptor = methodDescBuilder.toString();

        // Invoke method
        gv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, factoryInternalName, methodName, methodDescriptor, false);

        // Box primitive return types if necessary
        if (returnTypeMirror.getKind().isPrimitive()) {
            boxPrimitive(gv, returnTypeMirror.getKind());
        }

        gv.visitInsn(Opcodes.ARETURN);
        gv.visitMaxs(3, 1);
        gv.visitEnd();

        // create method
        MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "create",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                null, null);
        mv.visitCode();

        // Check if factoryInstance == null
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");
        Label nullCheckCreate = new Label();
        mv.visitJumpInsn(Opcodes.IFNONNULL, nullCheckCreate);

        // Create new factory instance
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitTypeInsn(Opcodes.NEW, factoryInternalName);
        mv.visitInsn(Opcodes.DUP);
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, factoryInternalName, "<init>", "()V", false);
        mv.visitFieldInsn(Opcodes.PUTFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        mv.visitLabel(nullCheckCreate);

        // Load factory instance
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        // Push method arguments from dependencies array
        for (int i = 0; i < parameters.size(); i++) {
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn(i);
            mv.visitInsn(Opcodes.AALOAD);
            emitCastToDeclaredType(mv, parameters.get(i).asType());
        }

        // Invoke method
        mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, factoryInternalName, methodName, methodDescriptor, false);

        // Box primitive return types if necessary
        if (returnTypeMirror.getKind().isPrimitive()) {
            boxPrimitive(mv, returnTypeMirror.getKind());
        }

        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(3, 2);
        mv.visitEnd();

        // getBeanType method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getBeanType",
                "()Ljava/lang/Class;",
                "()Ljava/lang/Class<T>;", null);
        mv.visitCode();
        mv.visitLdcInsn(Type.getType("L" + returnTypeInternalName + ";"));
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        // getDependencyCount method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getDependencyCount",
                "()I", null, null);
        mv.visitCode();
        mv.visitLdcInsn(parameters.size());
        mv.visitInsn(Opcodes.IRETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        cw.visitEnd();

        return cw.toByteArray();
    }

    /**
     * Gets the internal name for a type (e.g., "java/lang/String").
     */
    private String getInternalName(TypeMirror type) {
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) type;
            Element element = declaredType.asElement();
            String binaryName = getBinaryName((TypeElement) element);
            return binaryName.replace('.', '/');
        } else if (type.getKind().isPrimitive()) {
            switch (type.getKind()) {
                case INT: return "I";
                case LONG: return "J";
                case SHORT: return "S";
                case BYTE: return "B";
                case CHAR: return "C";
                case BOOLEAN: return "Z";
                case FLOAT: return "F";
                case DOUBLE: return "D";
                case VOID: return "V";
                default: throw new IllegalArgumentException("Unknown primitive: " + type.getKind());
            }
        } else if (type.getKind() == TypeKind.ARRAY) {
            // Handle array types
            TypeMirror componentType = ((javax.lang.model.type.ArrayType) type).getComponentType();
            return "[" + getDescriptor(componentType);
        }
        throw new IllegalArgumentException("Unsupported type: " + type);
    }

    /**
     * Gets the descriptor for a type (e.g., "Ljava/lang/String;" or "I").
     */
    private String getDescriptor(TypeMirror type) {
        if (type.getKind().isPrimitive()) {
            switch (type.getKind()) {
                case INT: return "I";
                case LONG: return "J";
                case SHORT: return "S";
                case BYTE: return "B";
                case CHAR: return "C";
                case BOOLEAN: return "Z";
                case FLOAT: return "F";
                case DOUBLE: return "D";
                case VOID: return "V";
                default: throw new IllegalArgumentException("Unknown primitive: " + type.getKind());
            }
        } else if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) type;
            Element element = declaredType.asElement();
            String binaryName = getBinaryName((TypeElement) element);
            return "L" + binaryName.replace('.', '/') + ";";
        } else if (type.getKind() == TypeKind.ARRAY) {
            TypeMirror componentType = ((javax.lang.model.type.ArrayType) type).getComponentType();
            return "[" + getDescriptor(componentType);
        }
        throw new IllegalArgumentException("Unsupported type: " + type);
    }

    /**
     * Gets the fully qualified type name from a TypeElement.
     */
    private String getFullyQualifiedTypeName(TypeElement element) {
        return element.getQualifiedName().toString();
    }

    /**
     * Gets the fully qualified type name from a TypeMirror.
     */
    private String getFullyQualifiedTypeName(TypeMirror typeMirror) {
        if (typeMirror.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) typeMirror;
            Element element = declaredType.asElement();
            if (element instanceof TypeElement) {
                return ((TypeElement) element).getQualifiedName().toString();
            }
        }
        return typeMirror.toString();
    }

    /**
     * Gets the package name from a TypeElement.
     */
    private String getPackageName(TypeElement element) {
        // Use Elements.getPackageOf() to correctly handle nested classes
        if (elements != null) {
            return elements.getPackageOf(element).getQualifiedName().toString();
        }
        // Fallback: traverse enclosing elements until we find the package
        Element enclosing = element.getEnclosingElement();
        while (enclosing != null && enclosing.getKind() != ElementKind.PACKAGE) {
            enclosing = enclosing.getEnclosingElement();
        }
        if (enclosing != null && enclosing.getKind() == ElementKind.PACKAGE) {
            String pkgName = enclosing.toString();
            return pkgName.equals("") ? "" : pkgName;
        }
        return "";
    }

    /**
     * Gets the binary name for a type (e.g., "com.pkg.Outer$Inner" for nested classes).
     * Uses Elements.getBinaryName() when available, otherwise falls back to manual construction.
     */
    private String getBinaryName(TypeElement element) {
        if (elements != null) {
            return elements.getBinaryName(element).toString();
        }
        // Fallback: construct binary name manually by traversing enclosing elements
        StringBuilder binaryName = new StringBuilder();
        buildBinaryNameRecursive(element, binaryName);
        return binaryName.toString();
    }

    /**
     * Recursively builds the binary name for nested classes using $ as separator.
     */
    private void buildBinaryNameRecursive(TypeElement element, StringBuilder result) {
        Element enclosing = element.getEnclosingElement();
        if (enclosing instanceof TypeElement) {
            // Recurse to build the outer class name first
            buildBinaryNameRecursive((TypeElement) enclosing, result);
            result.append('$');
        }
        // Append the simple name of this element
        if (result.length() > 0 && result.charAt(result.length() - 1) != '$') {
            // Add package separator if we have a package already
            result.append('.');
        }
        result.append(element.getQualifiedName().toString());
    }

    /**
     * Boxes a primitive value on the stack.
     */
    private void boxPrimitive(MethodVisitor mv, TypeKind kind) {
        String boxedType;
        String valueOfMethod;

        switch (kind) {
            case INT:
                boxedType = "java/lang/Integer";
                valueOfMethod = "valueOf";
                break;
            case LONG:
                boxedType = "java/lang/Long";
                valueOfMethod = "valueOf";
                break;
            case SHORT:
                boxedType = "java/lang/Short";
                valueOfMethod = "valueOf";
                break;
            case BYTE:
                boxedType = "java/lang/Byte";
                valueOfMethod = "valueOf";
                break;
            case CHAR:
                boxedType = "java/lang/Character";
                valueOfMethod = "valueOf";
                break;
            case BOOLEAN:
                boxedType = "java/lang/Boolean";
                valueOfMethod = "valueOf";
                break;
            case FLOAT:
                boxedType = "java/lang/Float";
                valueOfMethod = "valueOf";
                break;
            case DOUBLE:
                boxedType = "java/lang/Double";
                valueOfMethod = "valueOf";
                break;
            default:
                return; // Not a primitive
        }

        mv.visitMethodInsn(Opcodes.INVOKESTATIC, boxedType, valueOfMethod,
                "(" + getDescriptorForPrimitive(kind) + ")L" + boxedType + ";", false);
    }

    /**
     * Gets the descriptor for a primitive kind.
     */
    private String getDescriptorForPrimitive(TypeKind kind) {
        switch (kind) {
            case INT: return "I";
            case LONG: return "J";
            case SHORT: return "S";
            case BYTE: return "B";
            case CHAR: return "C";
            case BOOLEAN: return "Z";
            case FLOAT: return "F";
            case DOUBLE: return "D";
            default: throw new IllegalArgumentException("Not a primitive: " + kind);
        }
    }

    /**
     * Emits a {@code CHECKCAST} that converts a boxed dependency value (always an
     * {@code Object} in the dependency array / wired factory) to the declared injection type.
     *
     * <p>Reference types are cast directly. Primitive types are cast to their wrapper and then
     * unboxed, because dependency values travel as objects. Without the unboxing a primitive
     * injection point (constructor parameter, field or setter parameter) would emit an invalid
     * {@code CHECKCAST I} (etc.) and the generated factory would fail to verify with
     * {@code Bad type on operand stack}.</p>
     *
     * @param mv the method visitor
     * @param type the declared injection type of the target parameter/field
     */
    private void emitCastToDeclaredType(MethodVisitor mv, TypeMirror type) {
        if (type.getKind() == TypeKind.VOID) {
            return;
        }
        if (type.getKind().isPrimitive()) {
            String boxedType = boxedInternalName(type.getKind());
            mv.visitTypeInsn(Opcodes.CHECKCAST, boxedType);
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, boxedType,
                    unboxMethodName(type.getKind()),
                    "()" + getDescriptorForPrimitive(type.getKind()), false);
        } else {
            mv.visitTypeInsn(Opcodes.CHECKCAST, getInternalName(type));
        }
    }

    /**
     * Gets the internal name of the wrapper class for a primitive kind.
     */
    private String boxedInternalName(TypeKind kind) {
        switch (kind) {
            case INT: return "java/lang/Integer";
            case LONG: return "java/lang/Long";
            case SHORT: return "java/lang/Short";
            case BYTE: return "java/lang/Byte";
            case CHAR: return "java/lang/Character";
            case BOOLEAN: return "java/lang/Boolean";
            case FLOAT: return "java/lang/Float";
            case DOUBLE: return "java/lang/Double";
            default: throw new IllegalArgumentException("Not a primitive: " + kind);
        }
    }

    /**
     * Gets the name of the unboxing method for a primitive kind (e.g. {@code intValue}).
     */
    private String unboxMethodName(TypeKind kind) {
        switch (kind) {
            case INT: return "intValue";
            case LONG: return "longValue";
            case SHORT: return "shortValue";
            case BYTE: return "byteValue";
            case CHAR: return "charValue";
            case BOOLEAN: return "booleanValue";
            case FLOAT: return "floatValue";
            case DOUBLE: return "doubleValue";
            default: throw new IllegalArgumentException("Not a primitive: " + kind);
        }
    }

    /**
     * Simple adapter for Messager to allow testing.
     */
    public interface MessagerAdapter {
        void printError(String message, Element element);
    }
}
