package com.warmup.core.factory;

/**
 * Functional interface for compiled bean factories.
 * Generated by annotation processor (compile-time) or JIT compiler (runtime).
 * 
 * @param <T> The bean type to create
 */
@FunctionalInterface
public interface CompiledFactory<T> {
    /**
     * Creates a new instance of the bean.
     * For SINGLETON scope, the container caches the result.
     * For PROTOTYPE scope, this is called on every resolve().
     * 
     * @return A new bean instance
     */
    T create();
}
