package com.warmup.processor;

import com.warmup.annotations.Inject;
import org.objectweb.asm.*;

import javax.lang.model.element.*;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates bytecode for CompiledFactory implementations using ASM at compile-time.
 * 
 * This class produces the same factory structure as AsmJITCompiler.generateFactoryBytecode,
 * but works with TypeElement/TypeMirror instead of Class<?> since at compile-time the
 * user classes are not yet compiled and no Class objects are available.
 * 
 * Generated factory structure:
 * - Fields: dep0, dep1, ... for wired dependencies (type Object)
 * - Constructor: default empty constructor
 * - wire(Object[]): stores dependencies in fields
 * - get(): creates bean instance using wired dependencies (no Object[] allocation)
 * - create(Object...): fallback method for backward compatibility
 * - getBeanType(): returns the bean Class
 * - getDependencyCount(): returns total dependency count
 */
public class FactoryBytecodeGenerator {

    private final MessagerAdapter messager;

    public FactoryBytecodeGenerator(MessagerAdapter messager) {
        this.messager = messager;
    }

    /**
     * Generates bytecode for a class-level bean factory.
     * 
     * @param beanClass the TypeElement of the bean class
     * @param scope the scope of the bean (SINGLETON, PROTOTYPE, etc.)
     * @param explicitName the explicit bean name if provided
     * @param constructor the injectable constructor (may be null for no-arg)
     * @param injectFields list of fields annotated with @Inject
     * @param injectMethods list of methods annotated with @Inject (for setter injection)
     * @return the generated bytecode
     */
    public byte[] generateFactoryForClassBytecode(
            TypeElement beanClass,
            String scope,
            String explicitName,
            ExecutableElement constructor,
            List<VariableElement> injectFields,
            List<ExecutableElement> injectMethods) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

        String packageName = getPackageName(beanClass);
        String className = beanClass.getSimpleName().toString();
        String factoryClassName = packageName.isEmpty() ? className + "$$WarmupFactory" : packageName.replace('.', '/') + "/" + className + "$$WarmupFactory";
        String beanInternalName = packageName.isEmpty() ? className : packageName.replace('.', '/') + "/" + className;
        String interfaceName = "com/warmup/core/jit/CompiledFactory";

        // Class signature: CompiledFactory<BeanType>
        String signature = "L" + interfaceName + "<L" + beanInternalName + ";>;";

        // Class declaration: public final class Bean$$WarmupFactory implements CompiledFactory<BeanType>
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL, factoryClassName, null,
                "java/lang/Object", new String[]{interfaceName});

        // Collect all dependencies: constructor params + @Inject fields + @Inject method params
        List<? extends VariableElement> constructorParams = constructor != null ? constructor.getParameters() : new ArrayList<>();
        
        // Count total method parameters for dependency counting
        int methodParamCount = 0;
        for (ExecutableElement method : injectMethods) {
            methodParamCount += method.getParameters().size();
        }
        
        int totalDeps = constructorParams.size() + injectFields.size() + methodParamCount;

        // Declare fields for wired dependencies (dep0, dep1, ...)
        for (int i = 0; i < totalDeps; i++) {
            cw.visitField(Opcodes.ACC_PRIVATE, "dep" + i, "Ljava/lang/Object;", null, null);
        }

        // Default constructor
        MethodVisitor ctor = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitInsn(Opcodes.RETURN);
        ctor.visitMaxs(1, 1);
        ctor.visitEnd();

        // wire method: public void wire(CompiledFactory<?>[] dependencyFactories)
        if (totalDeps > 0) {
            MethodVisitor wv = cw.visitMethod(Opcodes.ACC_PUBLIC, "wire",
                    "([Lcom/warmup/core/jit/CompiledFactory;)V",
                    null, null);
            wv.visitCode();

            // For each dependency: this.dep[i] = dependencyFactories[i]
            for (int i = 0; i < totalDeps; i++) {
                // Load 'this'
                wv.visitVarInsn(Opcodes.ALOAD, 0);
                // Load dependencyFactories array
                wv.visitVarInsn(Opcodes.ALOAD, 1);
                // Push index
                wv.visitLdcInsn(i);
                // Load element: dependencyFactories[i]
                wv.visitInsn(Opcodes.AALOAD);
                // Store in field: this.dep{i}
                wv.visitFieldInsn(Opcodes.PUTFIELD, factoryClassName, "dep" + i, "Ljava/lang/Object;");
            }

            wv.visitInsn(Opcodes.RETURN);
            wv.visitMaxs(3, 2);
            wv.visitEnd();
        }

        // get method: public Object get()
        MethodVisitor gv = cw.visitMethod(Opcodes.ACC_PUBLIC, "get",
                "()Ljava/lang/Object;",
                "()T" + (beanInternalName.contains("/") ? ";" + beanInternalName.substring(beanInternalName.lastIndexOf('/') + 1).replace('/', '.') + ";" : ";" + className + ";"), null);
        gv.visitCode();

        // Create new instance of bean
        gv.visitTypeInsn(Opcodes.NEW, beanInternalName);
        gv.visitInsn(Opcodes.DUP);

        // Push constructor arguments from wired fields
        for (int i = 0; i < constructorParams.size(); i++) {
            // Load 'this'
            gv.visitVarInsn(Opcodes.ALOAD, 0);
            // Get field: this.dep{i}
            gv.visitFieldInsn(Opcodes.GETFIELD, factoryClassName, "dep" + i, "Ljava/lang/Object;");
            // Cast to dependency type
            TypeMirror paramType = constructorParams.get(i).asType();
            String paramInternalName = getInternalName(paramType);
            gv.visitTypeInsn(Opcodes.CHECKCAST, paramInternalName);
        }

        // Build constructor descriptor
        StringBuilder ctorDescBuilder = new StringBuilder("(");
        for (VariableElement param : constructorParams) {
            ctorDescBuilder.append(getDescriptor(param.asType()));
        }
        ctorDescBuilder.append(")V");
        String constructorDescriptor = ctorDescBuilder.toString();

        // Invoke constructor
        gv.visitMethodInsn(Opcodes.INVOKESPECIAL, beanInternalName, "<init>", constructorDescriptor, false);

        // Inject @Inject fields from remaining wired dependencies
        for (int i = 0; i < injectFields.size(); i++) {
            VariableElement field = injectFields.get(i);
            String fieldName = field.getSimpleName().toString();
            int fieldIndex = constructorParams.size() + i;

            // Load instance (already on stack after constructor call)
            gv.visitInsn(Opcodes.DUP);
            // Load 'this' (the factory)
            gv.visitVarInsn(Opcodes.ALOAD, 0);
            // Get field: this.dep{fieldIndex}
            gv.visitFieldInsn(Opcodes.GETFIELD, factoryClassName, "dep" + fieldIndex, "Ljava/lang/Object;");
            // Cast to field type
            TypeMirror fieldType = field.asType();
            String fieldInternalName = getInternalName(fieldType);
            gv.visitTypeInsn(Opcodes.CHECKCAST, fieldInternalName);
            // Put field: instance.fieldName = value
            String fieldDescriptor = getDescriptor(fieldType);
            gv.visitFieldInsn(Opcodes.PUTFIELD, beanInternalName, fieldName, fieldDescriptor);
        }

        // Invoke @Inject methods after field injection
        int methodParamStartIndex = constructorParams.size() + injectFields.size();
        for (ExecutableElement method : injectMethods) {
            String methodName = method.getSimpleName().toString();
            List<? extends VariableElement> methodParams = method.getParameters();
            
            // Build method descriptor
            StringBuilder methodDescBuilder = new StringBuilder("(");
            for (VariableElement param : methodParams) {
                methodDescBuilder.append(getDescriptor(param.asType()));
            }
            methodDescBuilder.append(")V");
            String methodDescriptor = methodDescBuilder.toString();
            
            // Load instance (already on stack)
            gv.visitInsn(Opcodes.DUP);
            
            // Push method arguments from wired deps
            int currentParamIndex = methodParamStartIndex;
            for (VariableElement param : methodParams) {
                // Load 'this' (the factory)
                gv.visitVarInsn(Opcodes.ALOAD, 0);
                // Get field: this.dep{currentParamIndex}
                gv.visitFieldInsn(Opcodes.GETFIELD, factoryClassName, "dep" + currentParamIndex, "Ljava/lang/Object;");
                // Cast to parameter type
                TypeMirror paramType = param.asType();
                String paramInternalName = getInternalName(paramType);
                gv.visitTypeInsn(Opcodes.CHECKCAST, paramInternalName);
                currentParamIndex++;
            }
            
            // Invoke the inject method
            gv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, beanInternalName, methodName, methodDescriptor, false);
            
            // Update start index for next method
            methodParamStartIndex += methodParams.size();
        }

        // Return the created instance
        gv.visitInsn(Opcodes.ARETURN);
        gv.visitMaxs(2 + constructorParams.size(), 1);
        gv.visitEnd();

        // create method: public Object create(Object... dependencies)
        MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "create",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                null, null);
        mv.visitCode();

        // Create new instance of bean
        mv.visitTypeInsn(Opcodes.NEW, beanInternalName);
        mv.visitInsn(Opcodes.DUP);

        // Push constructor arguments from dependencies array
        for (int i = 0; i < constructorParams.size(); i++) {
            // Load dependencies array
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            // Push index
            mv.visitLdcInsn(i);
            // Load element: dependencies[i]
            mv.visitInsn(Opcodes.AALOAD);
            // Cast to dependency type
            TypeMirror paramType = constructorParams.get(i).asType();
            String paramInternalName = getInternalName(paramType);
            mv.visitTypeInsn(Opcodes.CHECKCAST, paramInternalName);
        }

        // Invoke constructor
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, beanInternalName, "<init>", constructorDescriptor, false);

        // Inject @Inject fields from dependencies array (after constructor params)
        for (int i = 0; i < injectFields.size(); i++) {
            VariableElement field = injectFields.get(i);
            String fieldName = field.getSimpleName().toString();
            int fieldIndex = constructorParams.size() + i;

            // Load instance (already on stack after constructor call)
            mv.visitInsn(Opcodes.DUP);
            // Load dependencies array
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            // Push index
            mv.visitLdcInsn(fieldIndex);
            // Load element: dependencies[fieldIndex]
            mv.visitInsn(Opcodes.AALOAD);
            // Cast to field type
            TypeMirror fieldType = field.asType();
            String fieldInternalName = getInternalName(fieldType);
            mv.visitTypeInsn(Opcodes.CHECKCAST, fieldInternalName);
            // Put field: instance.fieldName = value
            String fieldDescriptor = getDescriptor(fieldType);
            mv.visitFieldInsn(Opcodes.PUTFIELD, beanInternalName, fieldName, fieldDescriptor);
        }

        // Invoke @Inject methods after field injection (create method path)
        int createMethodParamStartIndex = constructorParams.size() + injectFields.size();
        for (ExecutableElement method : injectMethods) {
            String methodName = method.getSimpleName().toString();
            List<? extends VariableElement> methodParams = method.getParameters();
            
            // Build method descriptor
            StringBuilder methodDescBuilder = new StringBuilder("(");
            for (VariableElement param : methodParams) {
                methodDescBuilder.append(getDescriptor(param.asType()));
            }
            methodDescBuilder.append(")V");
            String methodDescriptor = methodDescBuilder.toString();
            
            // Load instance (already on stack)
            mv.visitInsn(Opcodes.DUP);
            
            // Push method arguments from dependencies array
            int currentParamIndex = createMethodParamStartIndex;
            for (VariableElement param : methodParams) {
                // Load dependencies array
                mv.visitVarInsn(Opcodes.ALOAD, 1);
                // Push index
                mv.visitLdcInsn(currentParamIndex);
                // Load element: dependencies[currentParamIndex]
                mv.visitInsn(Opcodes.AALOAD);
                // Cast to parameter type
                TypeMirror paramType = param.asType();
                String paramInternalName = getInternalName(paramType);
                mv.visitTypeInsn(Opcodes.CHECKCAST, paramInternalName);
                currentParamIndex++;
            }
            
            // Invoke the inject method
            mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, beanInternalName, methodName, methodDescriptor, false);
            
            // Update start index for next method
            createMethodParamStartIndex += methodParams.size();
        }

        // Return the created instance
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(2 + constructorParams.size(), 2);
        mv.visitEnd();

        // getBeanType method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getBeanType",
                "()Ljava/lang/Class;",
                "()Ljava/lang/Class<T>;", null);
        mv.visitCode();
        mv.visitLdcInsn(Type.getType("L" + beanInternalName + ";"));
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        // getDependencyCount method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getDependencyCount",
                "()I", null, null);
        mv.visitCode();
        mv.visitLdcInsn(totalDeps);
        mv.visitInsn(Opcodes.IRETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        cw.visitEnd();

        return cw.toByteArray();
    }

    /**
     * Generates bytecode for a @Bean method factory.
     * 
     * @param factoryClass the TypeElement of the @Factory class
     * @param method the @Bean method
     * @param beanAnnotation the @Bean annotation
     * @return the generated bytecode
     */
    public byte[] generateFactoryForMethodBytecode(
            TypeElement factoryClass,
            ExecutableElement method,
            com.warmup.annotations.Bean beanAnnotation) {

        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);

        String packageName = getPackageName(factoryClass);
        String factoryClassNameStr = factoryClass.getSimpleName().toString();
        String methodName = method.getSimpleName().toString();
        String factoryInternalName = packageName.isEmpty() ? factoryClassNameStr : packageName.replace('.', '/') + "/" + factoryClassNameStr;
        
        TypeMirror returnTypeMirror = method.getReturnType();
        String returnTypeName = returnTypeMirror.toString();
        String returnTypeInternalName = getInternalName(returnTypeMirror);
        String returnTypeFqn = getFullyQualifiedTypeName(returnTypeMirror);
        
        String generatedFactoryName = packageName.isEmpty() ? factoryClassNameStr + "$$" + methodName + "$$WarmupFactory" 
                : packageName.replace('.', '/') + "/" + factoryClassNameStr + "$$" + methodName + "$$WarmupFactory";

        String interfaceName = "com/warmup/core/jit/CompiledFactory";

        // Class signature
        String signature = "L" + interfaceName + "<L" + returnTypeInternalName + ";>;";

        // Class declaration
        cw.visit(Opcodes.V17, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL, generatedFactoryName, null,
                "java/lang/Object", new String[]{interfaceName});

        // Field for caching the factory instance
        cw.visitField(Opcodes.ACC_PRIVATE, "factoryInstance", "L" + factoryInternalName + ";", null, null);

        // Get method parameters
        List<? extends VariableElement> parameters = method.getParameters();

        // Declare fields for dependency factories
        for (int i = 0; i < parameters.size(); i++) {
            cw.visitField(Opcodes.ACC_PRIVATE, "dep" + i, "Ljava/lang/Object;", null, null);
        }

        // Default constructor
        MethodVisitor ctor = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
        ctor.visitCode();
        ctor.visitVarInsn(Opcodes.ALOAD, 0);
        ctor.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        ctor.visitInsn(Opcodes.RETURN);
        ctor.visitMaxs(1, 1);
        ctor.visitEnd();

        // wire method
        if (!parameters.isEmpty()) {
            MethodVisitor wv = cw.visitMethod(Opcodes.ACC_PUBLIC, "wire",
                    "([Lcom/warmup/core/jit/CompiledFactory;)V",
                    null, null);
            wv.visitCode();

            for (int i = 0; i < parameters.size(); i++) {
                wv.visitVarInsn(Opcodes.ALOAD, 0);
                wv.visitVarInsn(Opcodes.ALOAD, 1);
                wv.visitLdcInsn(i);
                wv.visitInsn(Opcodes.AALOAD);
                wv.visitFieldInsn(Opcodes.PUTFIELD, generatedFactoryName, "dep" + i, "Ljava/lang/Object;");
            }

            wv.visitInsn(Opcodes.RETURN);
            wv.visitMaxs(3, 2);
            wv.visitEnd();
        }

        // get method
        MethodVisitor gv = cw.visitMethod(Opcodes.ACC_PUBLIC, "get",
                "()Ljava/lang/Object;",
                "()TT;", null);
        gv.visitCode();

        // Check if factoryInstance == null
        gv.visitVarInsn(Opcodes.ALOAD, 0);
        gv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");
        Label nullCheck = new Label();
        gv.visitJumpInsn(Opcodes.IFNONNULL, nullCheck);

        // Create new factory instance
        gv.visitVarInsn(Opcodes.ALOAD, 0);
        gv.visitTypeInsn(Opcodes.NEW, factoryInternalName);
        gv.visitInsn(Opcodes.DUP);
        gv.visitMethodInsn(Opcodes.INVOKESPECIAL, factoryInternalName, "<init>", "()V", false);
        gv.visitFieldInsn(Opcodes.PUTFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        gv.visitLabel(nullCheck);

        // Load factory instance
        gv.visitVarInsn(Opcodes.ALOAD, 0);
        gv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        // Push method arguments from wired deps
        for (int i = 0; i < parameters.size(); i++) {
            gv.visitVarInsn(Opcodes.ALOAD, 0);
            gv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "dep" + i, "Ljava/lang/Object;");
            TypeMirror paramType = parameters.get(i).asType();
            String paramInternalName = getInternalName(paramType);
            gv.visitTypeInsn(Opcodes.CHECKCAST, paramInternalName);
        }

        // Build method descriptor
        StringBuilder methodDescBuilder = new StringBuilder("(");
        for (VariableElement param : parameters) {
            methodDescBuilder.append(getDescriptor(param.asType()));
        }
        methodDescBuilder.append(")").append(getDescriptor(returnTypeMirror));
        String methodDescriptor = methodDescBuilder.toString();

        // Invoke method
        gv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, factoryInternalName, methodName, methodDescriptor, false);

        // Box primitive return types if necessary
        if (returnTypeMirror.getKind().isPrimitive()) {
            boxPrimitive(gv, returnTypeMirror.getKind());
        }

        gv.visitInsn(Opcodes.ARETURN);
        gv.visitMaxs(3, 1);
        gv.visitEnd();

        // create method
        MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "create",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                null, null);
        mv.visitCode();

        // Check if factoryInstance == null
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");
        Label nullCheckCreate = new Label();
        mv.visitJumpInsn(Opcodes.IFNONNULL, nullCheckCreate);

        // Create new factory instance
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitTypeInsn(Opcodes.NEW, factoryInternalName);
        mv.visitInsn(Opcodes.DUP);
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, factoryInternalName, "<init>", "()V", false);
        mv.visitFieldInsn(Opcodes.PUTFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        mv.visitLabel(nullCheckCreate);

        // Load factory instance
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitFieldInsn(Opcodes.GETFIELD, generatedFactoryName, "factoryInstance", "L" + factoryInternalName + ";");

        // Push method arguments from dependencies array
        for (int i = 0; i < parameters.size(); i++) {
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn(i);
            mv.visitInsn(Opcodes.AALOAD);
            TypeMirror paramType = parameters.get(i).asType();
            String paramInternalName = getInternalName(paramType);
            mv.visitTypeInsn(Opcodes.CHECKCAST, paramInternalName);
        }

        // Invoke method
        mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, factoryInternalName, methodName, methodDescriptor, false);

        // Box primitive return types if necessary
        if (returnTypeMirror.getKind().isPrimitive()) {
            boxPrimitive(mv, returnTypeMirror.getKind());
        }

        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(3, 2);
        mv.visitEnd();

        // getBeanType method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getBeanType",
                "()Ljava/lang/Class;",
                "()Ljava/lang/Class<T>;", null);
        mv.visitCode();
        mv.visitLdcInsn(Type.getType("L" + returnTypeInternalName + ";"));
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        // getDependencyCount method
        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getDependencyCount",
                "()I", null, null);
        mv.visitCode();
        mv.visitLdcInsn(parameters.size());
        mv.visitInsn(Opcodes.IRETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        cw.visitEnd();

        return cw.toByteArray();
    }

    /**
     * Gets the internal name for a type (e.g., "java/lang/String").
     */
    private String getInternalName(TypeMirror type) {
        if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) type;
            Element element = declaredType.asElement();
            String fqn = getFullyQualifiedTypeName((TypeElement) element);
            return fqn.replace('.', '/');
        } else if (type.getKind().isPrimitive()) {
            switch (type.getKind()) {
                case INT: return "I";
                case LONG: return "J";
                case SHORT: return "S";
                case BYTE: return "B";
                case CHAR: return "C";
                case BOOLEAN: return "Z";
                case FLOAT: return "F";
                case DOUBLE: return "D";
                case VOID: return "V";
                default: throw new IllegalArgumentException("Unknown primitive: " + type.getKind());
            }
        } else if (type.getKind() == TypeKind.ARRAY) {
            // Handle array types
            TypeMirror componentType = ((javax.lang.model.type.ArrayType) type).getComponentType();
            return "[" + getDescriptor(componentType).replace('/', '.');
        }
        throw new IllegalArgumentException("Unsupported type: " + type);
    }

    /**
     * Maps a type string to its internal name.
     */
    private String mapTypeToInternal(String typeStr) {
        // Handle primitives
        switch (typeStr) {
            case "int": return "I";
            case "long": return "J";
            case "short": return "S";
            case "byte": return "B";
            case "char": return "C";
            case "boolean": return "Z";
            case "float": return "F";
            case "double": return "D";
            case "void": return "V";
            default:
                // Reference type: replace dots with slashes
                return typeStr.replace('.', '/');
        }
    }

    /**
     * Gets the descriptor for a type (e.g., "Ljava/lang/String;" or "I").
     */
    private String getDescriptor(TypeMirror type) {
        if (type.getKind().isPrimitive()) {
            switch (type.getKind()) {
                case INT: return "I";
                case LONG: return "J";
                case SHORT: return "S";
                case BYTE: return "B";
                case CHAR: return "C";
                case BOOLEAN: return "Z";
                case FLOAT: return "F";
                case DOUBLE: return "D";
                case VOID: return "V";
                default: throw new IllegalArgumentException("Unknown primitive: " + type.getKind());
            }
        } else if (type.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) type;
            Element element = declaredType.asElement();
            String fqn = getFullyQualifiedTypeName((TypeElement) element);
            return "L" + fqn.replace('.', '/') + ";";
        } else if (type.getKind() == TypeKind.ARRAY) {
            TypeMirror componentType = ((javax.lang.model.type.ArrayType) type).getComponentType();
            return "[" + getDescriptor(componentType);
        }
        throw new IllegalArgumentException("Unsupported type: " + type);
    }

    /**
     * Gets the fully qualified type name from a TypeElement.
     */
    private String getFullyQualifiedTypeName(TypeElement element) {
        return element.getQualifiedName().toString();
    }

    /**
     * Gets the fully qualified type name from a TypeMirror.
     */
    private String getFullyQualifiedTypeName(TypeMirror typeMirror) {
        if (typeMirror.getKind() == TypeKind.DECLARED) {
            DeclaredType declaredType = (DeclaredType) typeMirror;
            Element element = declaredType.asElement();
            if (element instanceof TypeElement) {
                return ((TypeElement) element).getQualifiedName().toString();
            }
        }
        return typeMirror.toString();
    }

    /**
     * Gets the package name from a TypeElement.
     */
    private String getPackageName(TypeElement element) {
        Element enclosing = element.getEnclosingElement();
        if (enclosing.getKind() == ElementKind.PACKAGE) {
            String pkgName = enclosing.toString();
            return pkgName.equals("") ? "" : pkgName;
        }
        return "";
    }

    /**
     * Boxes a primitive value on the stack.
     */
    private void boxPrimitive(MethodVisitor mv, TypeKind kind) {
        String boxedType;
        String valueOfMethod;

        switch (kind) {
            case INT:
                boxedType = "java/lang/Integer";
                valueOfMethod = "valueOf";
                break;
            case LONG:
                boxedType = "java/lang/Long";
                valueOfMethod = "valueOf";
                break;
            case SHORT:
                boxedType = "java/lang/Short";
                valueOfMethod = "valueOf";
                break;
            case BYTE:
                boxedType = "java/lang/Byte";
                valueOfMethod = "valueOf";
                break;
            case CHAR:
                boxedType = "java/lang/Character";
                valueOfMethod = "valueOf";
                break;
            case BOOLEAN:
                boxedType = "java/lang/Boolean";
                valueOfMethod = "valueOf";
                break;
            case FLOAT:
                boxedType = "java/lang/Float";
                valueOfMethod = "valueOf";
                break;
            case DOUBLE:
                boxedType = "java/lang/Double";
                valueOfMethod = "valueOf";
                break;
            default:
                return; // Not a primitive
        }

        mv.visitMethodInsn(Opcodes.INVOKESTATIC, boxedType, valueOfMethod,
                "(" + getDescriptorForPrimitive(kind) + ")L" + boxedType + ";", false);
    }

    /**
     * Gets the descriptor for a primitive kind.
     */
    private String getDescriptorForPrimitive(TypeKind kind) {
        switch (kind) {
            case INT: return "I";
            case LONG: return "J";
            case SHORT: return "S";
            case BYTE: return "B";
            case CHAR: return "C";
            case BOOLEAN: return "Z";
            case FLOAT: return "F";
            case DOUBLE: return "D";
            default: throw new IllegalArgumentException("Not a primitive: " + kind);
        }
    }

    /**
     * Simple adapter for Messager to allow testing.
     */
    public interface MessagerAdapter {
        void printError(String message, Element element);
    }
}
