package com.warmup.processor;

import com.warmup.annotations.WarmupBean;
import com.warmup.annotations.WarmupInject;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.io.Writer;
import java.util.*;

/**
 * Annotation processor for generating compile-time CompiledFactory implementations.
 * 
 * Generates zero-overhead factories that are registered automatically with the container.
 * 
 * Supported annotations:
 * - @WarmupBean: Marks a class as a DI bean
 * - @WarmupInject: Marks constructor parameters for injection
 * 
 * Generated code example:
 * ```java
 * public class UserService$$WarmupFactory implements CompiledFactory<UserService> {
 *     private final CompiledFactory<Repository> repoFactory;
 *     
 *     public UserService$$WarmupFactory() {
 *         // Constructor
 *     }
 *     
 *     @Override
 *     public UserService create(Object... dependencies) {
 *         Repository repo = (Repository) dependencies[0];
 *         return new UserService(repo);
 *     }
 *     
 *     @Override
 *     public Class<UserService> getBeanType() {
 *         return UserService.class;
 *     }
 * }
 * ```
 */
@SupportedAnnotationTypes({
    "com.warmup.annotations.WarmupBean",
    "com.warmup.annotations.WarmupInject"
})
@SupportedSourceVersion(SourceVersion.RELEASE_17)
public class WarmupProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        Filer filer = processingEnv.getFiler();
        Messager messager = processingEnv.getMessager();
        
        // Process @WarmupBean annotated classes
        for (Element element : roundEnv.getElementsAnnotatedWith(WarmupBean.class)) {
            if (element.getKind() != ElementKind.CLASS) {
                messager.printMessage(Diagnostic.Kind.ERROR, 
                    "@WarmupBean only applies to classes", element);
                continue;
            }
            
            TypeElement typeElement = (TypeElement) element;
            WarmupBean warmupBean = typeElement.getAnnotation(WarmupBean.class);
            
            try {
                generateFactory(typeElement, warmupBean, filer);
            } catch (IOException e) {
                messager.printMessage(Diagnostic.Kind.ERROR, 
                    "Failed to generate factory: " + e.getMessage(), element);
            }
        }
        
        return true;
    }

    /**
     * Generates a CompiledFactory implementation for the given bean class.
     */
    private void generateFactory(TypeElement beanClass, WarmupBean annotation, Filer filer) 
            throws IOException {
        
        String packageName = getPackageName(beanClass);
        String className = beanClass.getSimpleName().toString();
        String factoryClassName = className + "$$WarmupFactory";
        
        // Find constructor and dependencies
        ExecutableElement constructor = findInjectableConstructor(beanClass);
        List<? extends VariableElement> parameters = constructor != null 
            ? constructor.getParameters() 
            : Collections.emptyList();
        
        StringBuilder code = new StringBuilder();
        code.append("package ").append(packageName).append(";\n\n");
        code.append("import com.warmup.core.jit.CompiledFactory;\n");
        code.append("import java.lang.Class;\n\n");
        
        // Generate factory class
        code.append("/**\n");
        code.append(" * Auto-generated factory for {@link ").append(className).append("}.\n");
        code.append(" * DO NOT MODIFY - generated by Warmup annotation processor\n");
        code.append(" */\n");
        code.append("@javax.annotation.Generated(\"com.warmup.processor.WarmupProcessor\")\n");
        code.append("public final class ").append(factoryClassName)
            .append(" implements CompiledFactory<").append(className).append("> {\n\n");
        
        // Generate fields for dependency factories (if any)
        for (int i = 0; i < parameters.size(); i++) {
            VariableElement param = parameters.get(i);
            String paramType = param.asType().toString();
            code.append("    private final CompiledFactory<").append(paramType)
                .append("> factory").append(i).append(";\n");
        }
        
        if (!parameters.isEmpty()) {
            code.append("\n");
        }
        
        // Generate constructor
        code.append("    public ").append(factoryClassName).append("() {\n");
        // In a full implementation, we would inject dependency factories here
        code.append("        // Dependencies resolved at runtime\n");
        for (int i = 0; i < parameters.size(); i++) {
            code.append("        this.factory").append(i).append(" = null;\n");
        }
        code.append("    }\n\n");
        
        // Generate create method
        code.append("    @Override\n");
        code.append("    public ").append(className).append(" create(Object... dependencies) {\n");
        
        // Cast dependencies
        for (int i = 0; i < parameters.size(); i++) {
            VariableElement param = parameters.get(i);
            String paramType = param.asType().toString();
            code.append("        ").append(paramType).append(" arg").append(i)
                .append(" = (").append(paramType).append(") dependencies[").append(i).append("];\n");
        }
        
        // Invoke constructor
        code.append("        return new ").append(className).append("(");
        for (int i = 0; i < parameters.size(); i++) {
            if (i > 0) code.append(", ");
            code.append("arg").append(i);
        }
        code.append(");\n");
        code.append("    }\n\n");
        
        // Generate getBeanType method
        code.append("    @Override\n");
        code.append("    public Class<").append(className).append("> getBeanType() {\n");
        code.append("        return ").append(className).append(".class;\n");
        code.append("    }\n\n");
        
        // Generate getDependencyCount method
        code.append("    @Override\n");
        code.append("    public int getDependencyCount() {\n");
        code.append("        return ").append(parameters.size()).append(";\n");
        code.append("    }\n");
        
        code.append("}\n");
        
        // Write the file
        Writer writer = filer.createSourceFile(packageName + "." + factoryClassName).openWriter();
        try {
            writer.write(code.toString());
        } finally {
            writer.close();
        }
    }

    /**
     * Finds the constructor to use for injection.
     * Prioritizes: @WarmupInject constructor > single public constructor > no-arg constructor
     */
    private ExecutableElement findInjectableConstructor(TypeElement beanClass) {
        ExecutableElement injectableConstructor = null;
        int publicConstructors = 0;
        ExecutableElement publicConstructor = null;
        
        for (Element enclosed : beanClass.getEnclosedElements()) {
            if (enclosed.getKind() != ElementKind.CONSTRUCTOR) {
                continue;
            }
            
            ExecutableElement constructor = (ExecutableElement) enclosed;
            
            // Check for @WarmupInject annotation
            if (constructor.getAnnotation(WarmupInject.class) != null) {
                return constructor;
            }
            
            // Track public constructors
            if (constructor.getModifiers().contains(Modifier.PUBLIC)) {
                publicConstructors++;
                publicConstructor = constructor;
            }
        }
        
        // Return single public constructor or no-arg constructor
        if (publicConstructors == 1 && publicConstructor != null) {
            return publicConstructor;
        }
        
        // Try to find no-arg constructor
        for (Element enclosed : beanClass.getEnclosedElements()) {
            if (enclosed.getKind() == ElementKind.CONSTRUCTOR) {
                ExecutableElement constructor = (ExecutableElement) enclosed;
                if (constructor.getParameters().isEmpty()) {
                    return constructor;
                }
            }
        }
        
        return null;
    }

    private String getPackageName(TypeElement type) {
        return processingEnv.getElementUtils()
            .getPackageOf(type).getQualifiedName().toString();
    }
}
